version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev:
        patterns:
          - "furo"
          - "html5lib"
          - "PyGithub"
          - "pyright"
          - "pytest-cov"
          - "pytest"
          - "requests"
          - "sphinx_design"
          - "sphinx-autobuild"
          - "sphinx"
          - "sybil"
          - "tox"
          - "tox-uv"
      style:
        patterns:
          - "prek"
          - "ruff"
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pre-commit:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gh-actions:
        patterns:
          - "*"
