# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev3+g0206414.d20230621'
__version_tuple__ = version_tuple = (0, 1, 'dev3', 'g0206414.d20230621')
