name: Test package
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
jobs:
  tests:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        include:
          - os: windows-latest
            python-version: "3.11"
          - os: macos-latest
            python-version: "3.11"
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          python -m pip install '.[test]'
      - name: Check codestyle
        run: black --check .
      - run: |
          echo 'Type "true"' > _empty_vhs_tape.tape
      - name: Install VHS
        uses: charmbracelet/vhs-action@v1
        with:
          path: _empty_vhs_tape.tape
      - name: Test package
        run: pytest -vv --showlocals --tb=short --color=yes --junit-xml=test-results.xml
      - name: Generate summary
        uses: pmeier/pytest-summary-gha@main
        if: always()
        with:
          path: test-results.xml
#  publish:
#    name: Publish to PyPi
#    runs-on: ubuntu-latest
#    needs: [ tests ]
#    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
#    steps:
#      - name: Checkout source
#        uses: actions/checkout@v3
#      - name: Set up python 3.8
#        uses: actions/setup-python@v4
#        with:
#          python-version: 3.8
#      - name: Install flit
#        run: |
#          pip install flit~=3.9
#      - name: Build and publish to test pypi
#        run: |
#          flit publish
#        env:
#          FLIT_USERNAME: __token__
#          FLIT_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
#          FLIT_INDEX_URL: https://test.pypi.org/legacy/
#      - name: Build and publish to pypi
#        run: |
#          flit publish
#        env:
#          FLIT_USERNAME: __token__
#          FLIT_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
